# Generated by Django 6.0 on 2026-02-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("laptops", "Laptops"),
                            ("audio", "Audio"),
                            ("wearables", "Wearables"),
                            ("accessories", "Accessories"),
                            ("limited", "Limited Edition"),
                        ],
                        default="laptops",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_new", models.BooleanField(default=False)),
                ("is_limited", models.BooleanField(default=False)),
                ("spec_1", models.CharField(blank=True, max_length=100)),
                ("spec_2", models.CharField(blank=True, max_length=100)),
                ("spec_3", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
